FROM jupyter/base-notebook:hub-1.1.0

USER root

COPY jupyter_notebook_config.py /etc/jupyter/
RUN fix-permissions /etc/jupyter/

RUN apt-get update && apt-get install -y git

USER $NB_UID

RUN python -m pip install nbgitpuller
