version: 2.1

orbs:
  slack: circleci/slack@3.4.2

commands:
  insert-image-database:
    steps:
      - run:
          name: request to aron-backend
          command: |
            curl -v -f -X POST https://api.dev.vssl.ai/api/v1/kernels_images/publish_new_managed_image \
              -H "Authorization: $KERNEL_IMAGE_PUBLISH_SECRET_KEY" \
              -H "Content-type: application/json" \
              -d "{\"image_url\": \"$IMAGE_TAG_NAME\"}"
  push-docker-image:
    parameters:
      filename:
        type: string
      repo:
        type: string
        default: test
      tag:
        default: latest
        type: string
      path:
        default: ngc
        type: string
    steps:
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: docker login
          command: docker login -u $QUAY_ACCOUNT_USERNAME -p $QUAY_ACCOUNT_PASSWORD quay.io
      - run:
          name: store image tag
          command: |
            export TAG="$QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>-$(date +'%Y%m%d%H%M')"
            echo "export IMAGE_TAG_NAME=$TAG" >> "$BASH_ENV"
            source "$BASH_ENV"
      - run:
          name: docker build
          command: cd ./<<parameters.path>> && docker build --build-arg NGC_TAG=<<parameters.tag>> -f Dockerfile.<<parameters.filename>> -t $IMAGE_TAG_NAME .
      - run:
          name: docker push
          command: docker push $IMAGE_TAG_NAME
          no_output_timeout: 1h

jobs:
  push-tf1-ngc-prev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$(date -d '-1 months' '+%y.%m')-tf1-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
      - slack/status:
          include_project_field: false
          include_job_number_field: false
          failure_message: ':alert: $IMAGE_TAG_NAME Publish Fail! \n'
          success_message: ':blob-clap: <https://github.com/${CIRCLE_USERNAME}|*${CIRCLE_USERNAME}*>\n
          Check out Release Notes <https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/index.html*>'
  push-tf1-ngc-cur:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$(date '+%y.%m')-tf1-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-tf2-ngc-prev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$(date -d '-1 months' '+%y.%m')-tf2-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-tf2-ngc-cur:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$(date '+%y.%m')-tf2-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-pytorch-ngc-prev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "$(date -d '-1 months' '+%y.%m')-py3"
          repo: "ngc-pytorch-kernel"
      - insert-image-database
  push-pytorch-ngc-cur:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "$(date '+%y.%m')-py3"
          repo: "ngc-pytorch-kernel"
      - insert-image-database
  push-py3x-cpu:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py310"
          tag: "py310"
          path: "cpu"

workflows: 
  main:  
    jobs:
      - push-tf1-ngc-prev:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-tf1-ngc-cur:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-tf2-ngc-prev:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-tf2-ngc-cur:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-pytorch-ngc-prev:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-pytorch-ngc-cur:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-py3x-cpu:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005