version: 2.1

commands:
  push-docker-image:
    parameters:
      repo:
        type: string
      tag:
        default: latest
        type: string
    steps:
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: docker login
          command: docker login -u $QUAY_FRONTEND_ACCOUNT_USERNAME -p $QUAY_FRONTEND_ACCOUNT_PASSWORD quay.io
      - run:
          name: docker build
          command: docker build -f ./ngc/Dockerfile.<<parameters.repo>> -t $QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>> .
      - run:
          name: docker push
          command: docker push $QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>


jobs:
  push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          repo: "py3-tf2-ngc"
          tag: "22.04"
    

workflows: 
  main:  
    jobs:
      - push:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main
                - vssl-4006