version: 2.1

commands:
  push-docker-image:
    parameters:
      filename:
        type: string
      repo:
        type: string
        default: test
      tag:
        default: latest
        type: string
      path:
        default: ngc
        type: string
    steps:
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: docker login
          command: docker login -u $QUAY_ACCOUNT_USERNAME -p $QUAY_ACCOUNT_PASSWORD quay.io
      - run:
          name: store timestamp
          command: export TAG_DATE=$(date +'%Y%m%d%H%M')
      - run:
          name: docker build
          command: docker build --build-arg NGC_TAG=<<parameters.tag>> -f ./<<parameters.path>>/Dockerfile.<<parameters.filename>> -t $QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>-$TAG_DATE .
      - run:
          name: docker push
          command: docker push $QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>-$TAG_DATE


jobs:
  push-tf1-ngc:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "22.04-tf1-py3"
  push-tf2-ngc:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "22.04-tf2-py3"
  push-torch-ngc:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "22.04-py3"
  push-py3x-cpu:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py310"
          tag: "py310"
          path: "cpu"

workflows: 
  main:  
    jobs:
      - push-tf1-ngc:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main
                - vssl-4006
      - push-tf2-ngc:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main
                - vssl-4006
      - push-torch-ngc:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main
                - vssl-4006
      - push-py3x-cpu:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main
                - vssl-4006