version: 2.1

commands:
  insert-image-database:
    step:
      - run:
          name: request to aron-backend
          command: curl -v -X POST https://api.dev.vssl.ai/api/v1/kernels_images/publish_new_managed_image \
          -H "Authorization: $KERNEL_IMAGE_PUBLISH_SECRET_KEY \
          -H "Content-type: application/json" \
          -d '{"image_url": $IMAGE_TAG_NAME}'
  push-docker-image:
    parameters:
      filename:
        type: string
      repo:
        type: string
        default: test
      tag:
        default: latest
        type: string
      path:
        default: ngc
        type: string
    steps:
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: docker login
          command: docker login -u $QUAY_ACCOUNT_USERNAME -p $QUAY_ACCOUNT_PASSWORD quay.io
      - run:
          name: store image tag
          command: |
            echo 'export IMAGE_TAG_NAME=$QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>-$(date +'%Y%m%d%H%M')' >> "$BASH_ENV"
            source "$BASH_ENV"
      - run:
          name: docker build
          command: cd ./<<parameters.path>> && docker build --build-arg NGC_TAG=<<parameters.tag>> -f Dockerfile.<<parameters.filename>> -t $IMAGE_TAG_NAME .
      - run:
          name: docker push
          command: docker push $QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>-$TAG_DATE

jobs:
  push-tf1-ngc:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          # only can use on linux os
          tag: "$(date -d "-1 months" '+%y.%m')-tf1-py3"
      - insert-image-database
  push-tf2-ngc:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "22.04-tf2-py3"
  push-torch-ngc:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "22.04-py3"
  push-py3x-cpu:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py310"
          tag: "py310"
          path: "cpu"

workflows: 
  main:  
    jobs:
      - push-tf1-ngc:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-tf2-ngc:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-torch-ngc:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005
      - push-py3x-cpu:
          context:
            - quay-creds
            - kernel-image-publish-secrets
          filters:
            branches:
              only:
                - main
                - vssl-4005