version: 2.1

orbs:
  slack: circleci/slack@3.4.2

commands:
  push-docker-image:
    steps:
      - run:
          name: docker push
          command: |
            docker push "${QUAY_ACCOUNT_URL}/tmp:tmp-cuda12.1-torch2.2"
            docker push "${QUAY_ACCOUNT_URL}/tmp:tmp-cuda12.1-torch2.3"
          no_output_timeout: 1h

  build-docker-image:
    steps:
      - setup_remote_docker:
            version: default
            docker_layer_caching: true
      - run:
          name: docker login
          command: docker login -u $QUAY_ACCOUNT_USERNAME -p $QUAY_ACCOUNT_PASSWORD quay.io
      - run:
          name: docker build
          command: |
            cd ./cuda
            docker build -f Dockerfile --target torch-2.2 -t "${QUAY_ACCOUNT_URL}/tmp:tmp-cuda12.1-torch2.2" .
            docker build -f Dockerfile --target torch-2.3 -t "${QUAY_ACCOUNT_URL}/tmp:tmp-cuda12.1-torch2.3" .

executors:
  kernel-image-publishing-docker:
    resource_class: xlarge
    docker:
      - image: cimg/base:stable

jobs:
  tmp-push-cuda-torch:
    executor: kernel-image-publishing-docker
    steps:
      - checkout
      - build-docker-image
      - push-docker-image

workflows: 
  main:
    jobs:
      - tmp-push-cuda-torch:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - amelia/cuda