version: 2.1

commands:
  insert-image-database:
    steps:
      - run:
          name: request to aron-backend
          command: |
            curl -v -f -X POST https://api.dev.vssl.ai/api/v1/kernels_images/publish_new_managed_image \
              -H "Authorization: $KERNEL_IMAGE_PUBLISH_SECRET_KEY" \
              -H "Content-type: application/json" \
              -d "{\"image_url\": \"$IMAGE_TAG_NAME\"}"
  push-docker-image:
    parameters:
      filename:
        type: string
      repo:
        type: string
        default: test
      tag:
        default: latest
        type: string
      path:
        default: ngc
        type: string
    steps:
      - setup_remote_docker:
            version: 20.10.17
            docker_layer_caching: true
      - run:
          name: docker login
          command: docker login -u $QUAY_ACCOUNT_USERNAME -p $QUAY_ACCOUNT_PASSWORD quay.io
      - run:
          name: store image tag
          command: |
            export TAG="$QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>-$DATE"
            echo "export IMAGE_TAG_NAME=$TAG" >> "$BASH_ENV"
            source "$BASH_ENV"
      - run:
          name: docker build
          command: |
            cd ./<<parameters.path>> &&  docker build --build-arg NGC_TAG=<<parameters.tag>> -f Dockerfile.<<parameters.filename>> -t $IMAGE_TAG_NAME .
      - run:
          name: docker push
          command: |
            docker push $IMAGE_TAG_NAME
          no_output_timeout: 1h

executors:
  kernel-imnge-publising-docker:
    resource_class: xlarge
    docker:
      - image: cimg/base:stable

jobs:
  push-tf1-ngc-1704:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=17.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: $NGC_TAG_VERSION-tf1-py3
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-tf2-ngc-1704:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=17.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$NGC_TAG_VERSION-tf2-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-pytorch-ngc-1704:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=17.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "$NGC_TAG_VERSION-py3"
          repo: "ngc-pytorch-kernel"
      - insert-image-database
  push-tf1-ngc-1804:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=18.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: $NGC_TAG_VERSION-tf1-py3
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-tf2-ngc-1804:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=18.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$NGC_TAG_VERSION-tf2-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-pytorch-ngc-1804:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=18.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "$NGC_TAG_VERSION-py3"
          repo: "ngc-pytorch-kernel"
      - insert-image-database
  push-tf1-ngc-1904:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=19.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: $NGC_TAG_VERSION-tf1-py3
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-tf2-ngc-1904:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=19.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$NGC_TAG_VERSION-tf2-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-pytorch-ngc-1904:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=19.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "$NGC_TAG_VERSION-py3"
          repo: "ngc-pytorch-kernel"
      - insert-image-database
  push-tf1-ngc-2004:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=20.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: $NGC_TAG_VERSION-tf1-py3
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-tf2-ngc-2004:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=20.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$NGC_TAG_VERSION-tf2-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-pytorch-ngc-2004:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=20.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "$NGC_TAG_VERSION-py3"
          repo: "ngc-pytorch-kernel"
      - insert-image-database
  push-tf1-ngc-2104:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=21.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: $NGC_TAG_VERSION-tf1-py3
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-tf2-ngc-2104:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=21.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "$NGC_TAG_VERSION-tf2-py3"
          repo: "ngc-tensorflow-kernel"
      - insert-image-database
  push-pytorch-ngc-2104:
    executor: kernel-imnge-publising-docker
    steps:
      - checkout
      - run:
          name: store variables
          command: |
            echo "export DATE=$(date +'%Y%m%d%H%M')" >> "$BASH_ENV"
            echo "export NGC_TAG_VERSION=21.04" >> "$BASH_ENV"
            source "$BASH_ENV"
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "$NGC_TAG_VERSION-py3"
          repo: "ngc-pytorch-kernel"
      - insert-image-database
  
workflows: 
  main:
    jobs:
      - push-tf1-ngc-1704:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf2-ngc-1704:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-pytorch-ngc-1704:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf1-ngc-1804:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf2-ngc-1804:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-pytorch-ngc-1804:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf1-ngc-1904:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf2-ngc-1904:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-pytorch-ngc-1904:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf1-ngc-2004:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf2-ngc-2004:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-pytorch-ngc-2004:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf1-ngc-2104:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-tf2-ngc-2104:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish
      - push-pytorch-ngc-2104:
          context:
            - quay-creds
            - kernel-image-publish-secrets
            - slack-webhook-for-v3-orb
          filters:
            branches:
              only:
                - force-image-publish