version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/build-config.yml
          mapping: |
            cpu/.* build-cpu true
            ngc/.* build-ngc true
            hub/.* build-hub true
            background-container/.* build-background-container true
