version: 2.1

commands:
  push-docker-image:
    parameters:
      filename:
        type: string
      repo:
        type: string
        default: test
      tag:
        default: latest
        type: string
    steps:
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: docker login
          command: docker login -u $QUAY_FRONTEND_ACCOUNT_USERNAME -p $QUAY_FRONTEND_ACCOUNT_PASSWORD quay.io
      - run:
          name: docker build
          command: docker build -f ./ngc/Dockerfile.<<parameters.filename>> -t $QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>> .
      - run:
          name: docker push
          command: docker push $QUAY_ACCOUNT_URL/<<parameters.repo>>:<<parameters.tag>>


jobs:
  push-tf1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "tf1-22.04"
  push-tf2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-tf-ngc"
          tag: "tf2-22.04"
  push-torch:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - push-docker-image:
          filename: "py3-torch-ngc"
          tag: "22.04"
    

workflows: 
  main:  
    jobs:
      - push-tf1:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main
      - push-tf2:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main
      - push-torch:
          context:
            - quay-creds
          filters:
            branches:
              only:
                - main