all:
	docker build -t gcr.io/savvy-kit-260206/aron-backend-kernel:py3.6-tf1.14 --build-arg PYTHON_VERSION=3.6 --build-arg TF_PACKAGE_VERSION=1.14 .
	docker push gcr.io/savvy-kit-260206/aron-backend-kernel:py3.6-tf1.14

