# Ubuntu 18.04 comes with Python 3.6
FROM ubuntu:18.04

MAINTAINER floyd@savvihub.com

ENV DEBIAN_FRONTEND=noninteractive \
	PYTHONUNBUFFERED=1 \
    PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8 \
    SHELL=/bin/bash

USER root

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y \
        ca-certificates curl \
        gcc g++ git git-core \
        libgeos-dev libgeos++-dev libmpdec2 libproj-dev libssl-dev \
        mime-support \
        proj-bin python3 python3-pip \
        sudo \
        vim-tiny \
        unzip \
        zip \
        wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
  	apt-get install -y nodejs  && \
  	rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py | python3 && \
  	pip install --upgrade pip && \
  	pip install --upgrade Cython "numpy<1.17"

RUN pip install --upgrade \
		jupyterlab==1.2.6 \
		ipywidgets \
		plotly \
		bokeh \
		scipy \
		numexpr \
		patsy \
		scikit-learn \
		scikit-image \
		matplotlib \
		ipython \
		pandas \
		sympy \
		seaborn \
		nose \
		Cartopy==0.16 \
		cvxpy \
		h5py \
		ipywidgets \
		networkx \
		numexpr \
		pillow \
		pygments \
		tqdm && \
	rm -rf /root/.cache && \
	rm -f /tmp/*.whl

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 2

COPY start-notebook.sh /usr/local/bin/
COPY config/ /root/.jupyter/
