FROM quay.io/vessl-ai/ngc-pytorch-kernel:23.10-py3-202311150327

# Install git-lfs
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash \
    && apt-get install git-lfs \
    && git lfs install
