apiVersion: v1
kind: Pod
metadata:
  name: mxnet-gpu-pod
spec:
  containers:
  - name: mxnet-gpu-container
    image: gcr.io/savvy-kit-260206/aron-backend-kernel:mxnet1.6.0-gpu
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-k80
  imagePullPolicy: Always
  imagePullSecrets:
    - name: gcr-registry
